# name of workflow that will be displayed on the actions page
name: Plot views

# execute workflow only when these files are modified
on:
#  schedule:
#    - cron: '5 * * * *'
  workflow_dispatch:

# a list of the jobs that run as part of the workflow
jobs:
  plot_view:
    runs-on: ubuntu-latest

    # the type of runner to run the given job
    container: davetang/rstudio:4.2.0

    # a list of the steps that will run as part of the job
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."

      - name: Plot views
        run: code/plot_view.R https://davetang.org/site_stat/blog_views.csv.gz

      - name: Install wput
        run: |
          sudo apt update
          sudo apt install -y wput
      
      - name: FTP put
        run: wput output/views.png ftp://${{ secrets.FTPUSER }}:${{ secrets.FTPPASS }}@davetang.org

      - run: echo "This job's status is ${{ job.status }}."
